import { IBooking } from "@/common/entity/IDBBooking";

export const bookingData: IBooking[] = [
  {
    id: 1,
    user_id: 1,
    customer_name: "Alice Johnson",
    customer_email: "alice@example.com",
    booking_date: "2025-04-14",
    booking_type: "full_day",
    booking_slot: "first_half",
    from_time: null,
    to_time: null,
    created_at: "2025-04-12T10:00:00Z",
  },
  {
    id: 2,
    user_id: 2,
    customer_name: "Bob Smith",
    customer_email: "bob@example.com",
    booking_date: "2025-04-14",
    booking_type: "half_day",
    booking_slot: "first_half",
    from_time: null,
    to_time: null,
    created_at: "2025-04-12T10:05:00Z",
  },
  {
    id: 3,
    user_id: 3,
    customer_name: "Carol Miller",
    customer_email: "carol@example.com",
    booking_date: "2025-04-15",
    booking_type: "half_day",
    booking_slot: "second_half",
    from_time: null,
    to_time: null,
    created_at: "2025-04-12T10:10:00Z",
  },
  {
    id: 4,
    user_id: 4,
    customer_name: "David Lee",
    customer_email: "david@example.com",
    booking_date: "2025-04-15",
    booking_type: "custom",
    booking_slot: "second_half",
    from_time: "10:00:00",
    to_time: "12:30:00",
    created_at: "2025-04-12T10:15:00Z",
  },
  {
    id: 5,
    user_id: 1,
    customer_name: "Eva Green",
    customer_email: "eva@example.com",
    booking_date: "2025-04-16",
    booking_type: "custom",
    booking_slot: "second_half",
    from_time: "14:00:00",
    to_time: "16:00:00",
    created_at: "2025-04-12T10:20:00Z",
  },
];
